import { Header } from '@/shared/components/shared/header';
import type { Metadata } from 'next';
import { ReactNode } from 'react';

export const metadata: Metadata = {
    title: 'Next Pizza',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: ReactNode;
    modal: ReactNode;
}>) {
    return (
        <html lang="ru">
            <Header isShowDrawer isShowSearch />
            <main className="min-h-screen">
                {children}
                {modal}
            </main>
        </html>
    );
}
