import { Container, Header } from '@/shared/components/shared';
import { Suspense } from 'react';

export const metadata = {
    title: 'Next Pizza | Checkout',
    description: 'Generated by Next.js',
};

export default function CheckoutLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <main className="min-h-screen bg-[#F4F1EE]">
                <Container>
                    <Suspense>
                        <Header />
                    </Suspense>
                    {children}
                </Container>
            </main>
        </html>
    );
}
